EXP:
    ID: SUN397
    OUTPUT_DIR: SUN397_RESULTS

DATASET:
    NAME: SUN397
    ROOT: ./Data/Datasets/
    SCENE_LABELS: ./Data/Datasets/SUN397/scene_names.txt
    SEM_LABELS: ./Data/Datasets/ADEChallengeData2016/objectInfo150.txt
    N_CLASSES_SCENE: 397
    N_CLASSES_SEM: 151

DATALOADER:
    NUM_WORKERS: 0

MODEL:
    ARCH: ResNet-50
    PATH: ./Data/Model Zoo/SUN397/
    NAME: SAScene_ResNet50_SUN
    ONLY_RGB: FALSE
    ONLY_SEM: FALSE

TRAINING:
    PRINT_FREQ: 10
    PRECOMPUTED_SEM: TRUE
    BATCH_SIZE:
        TRAIN: 100
        TEST: 1
    LR: 2.5e-4
    LR_DECAY: 10
    MOMENTUM: 0.9
    OPTIMIZER: DFW
    POLY_POWER: 0.9
    WEIGHT_DECAY: 5.0e-4
    AVERAGE_LOSS: 20

VALIDATION:
    PRINT_FREQ: 10
    BATCH_SIZE:
        TRAIN: 100
        TEST: 1
    TEN_CROPS: TRUE
